version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "composer install --prefer-dist --no-progress"
      - run:
          name: "Execute tests"
          command: "vendor/bin/phpunit --coverage-clover coverage.xml"
      - store_artifacts:
          path: coverage.xml
          destination: circleci-docs

workflows:
  build-workflow:
    jobs:
      - build
