name: Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Execute tests
        run: |
          XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v