name: Test
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Execute tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Upload tests results
        uses: actions/upload-artifact@v2
        with:
          name: phpunit
          path: |
            coverage.xml
            phpunit.xml

  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download tests results
        uses: actions/download-artifact@v2
        with:
          name: phpunit

      - name: Dump
        run: ls -Al