name: Test
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache README.md
        id: cache-readme
        with:
          path: README.md
          key: ${{ runner.os }}-readme

  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        name: Restore README.md
        with:
          path: README.md
          key: ${{ runner.os }}-readme
          restore-keys: ${{ runner.os }}-readme

      - name: Dump
        run: ls -Al